parameters:
#    orang_medic.example.class: OrangMedic\OrangMedicBundle\Example

services:
#    orang_medic.example:
#        class: %orang_medic.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
