<?php

namespace Proxies\__CG__\OrangMedic\OrangMedicBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Commande extends \OrangMedic\OrangMedicBundle\Entity\Commande implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'OrangMedic\\OrangMedicBundle\\Entity\\Commande' . "\0" . 'prix', '' . "\0" . 'OrangMedic\\OrangMedicBundle\\Entity\\Commande' . "\0" . 'qtetotale', '' . "\0" . 'OrangMedic\\OrangMedicBundle\\Entity\\Commande' . "\0" . 'datedecommande', '' . "\0" . 'OrangMedic\\OrangMedicBundle\\Entity\\Commande' . "\0" . 'etat', '' . "\0" . 'OrangMedic\\OrangMedicBundle\\Entity\\Commande' . "\0" . 'adresse', '' . "\0" . 'OrangMedic\\OrangMedicBundle\\Entity\\Commande' . "\0" . 'idcmd', '' . "\0" . 'OrangMedic\\OrangMedicBundle\\Entity\\Commande' . "\0" . 'emailClient', '' . "\0" . 'OrangMedic\\OrangMedicBundle\\Entity\\Commande' . "\0" . 'libelle');
        }

        return array('__isInitialized__', '' . "\0" . 'OrangMedic\\OrangMedicBundle\\Entity\\Commande' . "\0" . 'prix', '' . "\0" . 'OrangMedic\\OrangMedicBundle\\Entity\\Commande' . "\0" . 'qtetotale', '' . "\0" . 'OrangMedic\\OrangMedicBundle\\Entity\\Commande' . "\0" . 'datedecommande', '' . "\0" . 'OrangMedic\\OrangMedicBundle\\Entity\\Commande' . "\0" . 'etat', '' . "\0" . 'OrangMedic\\OrangMedicBundle\\Entity\\Commande' . "\0" . 'adresse', '' . "\0" . 'OrangMedic\\OrangMedicBundle\\Entity\\Commande' . "\0" . 'idcmd', '' . "\0" . 'OrangMedic\\OrangMedicBundle\\Entity\\Commande' . "\0" . 'emailClient', '' . "\0" . 'OrangMedic\\OrangMedicBundle\\Entity\\Commande' . "\0" . 'libelle');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Commande $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setPrix($prix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', array($prix));

        return parent::setPrix($prix);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', array());

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setQtetotale($qtetotale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQtetotale', array($qtetotale));

        return parent::setQtetotale($qtetotale);
    }

    /**
     * {@inheritDoc}
     */
    public function getQtetotale()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQtetotale', array());

        return parent::getQtetotale();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatedecommande($datedecommande)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatedecommande', array($datedecommande));

        return parent::setDatedecommande($datedecommande);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatedecommande()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatedecommande', array());

        return parent::getDatedecommande();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat($etat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', array($etat));

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', array());

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', array($adresse));

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', array());

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdcmd()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getIdcmd();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcmd', array());

        return parent::getIdcmd();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailClient(\OrangMedic\OrangMedicBundle\Entity\Client $emailClient = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailClient', array($emailClient));

        return parent::setEmailClient($emailClient);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailClient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailClient', array());

        return parent::getEmailClient();
    }

    /**
     * {@inheritDoc}
     */
    public function addLibelle(\OrangMedic\OrangMedicBundle\Entity\Produits $libelle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLibelle', array($libelle));

        return parent::addLibelle($libelle);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLibelle(\OrangMedic\OrangMedicBundle\Entity\Produits $libelle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLibelle', array($libelle));

        return parent::removeLibelle($libelle);
    }

    /**
     * {@inheritDoc}
     */
    public function getLibelle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibelle', array());

        return parent::getLibelle();
    }

}
